### ISSUE TITLE
Install fails on windows 10 due to characer encoding issue in README.rst

### ISSUE THREAD

**Issue by skelsec** [savon-noir/python-libnmap#123]
# Problem
When installing either via `pip install` or `python setup.py install`  the install script fails almost immediately.  
# Platform
Python version:  
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```  
Windows version:  
```Microsoft Windows [Version 10.0.15063]```
# Error
```
XXXX > python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    long_description = rfile.read()
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1117: character maps to <undefined>
```  
# Reason
Quote characters at positions  around the words `diff()ed` and `NmapReport`

**Comment by savon-noir** [comment]
relates to this PR/ https://github.com/savon-noir/python-libnmap/pull/120 .. I'll merge and republish this week.
