### ISSUE TITLE
libnmap.objects.NmapService.scripts_results always returns empty dict

### ISSUE THREAD

**Issue by trashgordon-zz** [savon-noir/python-libnmap#14]
I ran an Nmap scan (outside of python-libnmap) as follows:
nmap -p139,445 --script=smb-os-discovery -oX smb-os-test.xml 192.168.31.205
## In the smb-os-test.xml file, I can see that the NSE script results are included:

<?xml version="1.0"?>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>

<nmaprun scanner="nmap" args="nmap -p139,445 -&#45;script=smb-os-discovery -oX smb-os-test.xml 192.168.31.205" start="1393887829" startstr="Mon Mar  3 17:03:49 2014" version="6.40" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="2" services="139,445"/>
<verbose level="0"/>
<debugging level="0"/>
<host starttime="1393887829" endtime="1393887832"><status state="up" reason="arp-response" reason_ttl="0"/>
<address addr="192.168.31.205" addrtype="ipv4"/>
<address addr="AA:BB:CC:DD:EE:FF" addrtype="mac" vendor="VMware"/>
<hostnames>
</hostnames>
<ports><port protocol="tcp" portid="139"><state state="open" reason="syn-ack" reason_ttl="128"/><service name="netbios-ssn" method="table" conf="3"/></port>
<port protocol="tcp" portid="445"><state state="open" reason="syn-ack" reason_ttl="128"/><service name="microsoft-ds" method="table" conf="3"/></port>
</ports>
<hostscript><script id="smb-os-discovery" output="&#xa;  OS: Windows 2000 (Windows 2000 LAN Manager)&#xa;  OS CPE: cpe:/o:microsoft:windows_2000::-&#xa;  Computer name: oracle&#xa;  NetBIOS computer name: ORACLE&#xa;  Domain name: acme.local&#xa;  FQDN: oracle.acme.local&#xa;  NetBIOS domain name: ACME&#xa;  System time: 2014-03-03T16:41:35+02:00&#xa;"><elem key="os">Windows 5.0</elem>
<elem key="lanmanager">Windows 2000 LAN Manager</elem>
<elem key="domain">ACME</elem>
<elem key="server">ORACLE</elem>
<elem key="date">2014-03-03T16:41:35+02:00</elem>
<elem key="fqdn">oracle.acme.local</elem>
<elem key="domain_dns">acme.local</elem>
<elem key="cpe">cpe:/o:microsoft:windows_2000::-</elem>
</script></hostscript><times srtt="83859" rttvar="50288" to="285011"/>
</host>
<runstats><finished time="1393887832" timestr="Mon Mar  3 17:03:52 2014" elapsed="2.46" summary="Nmap done at Mon Mar  3 17:03:52 2014; 1 IP address (1 host up) scanned in 2.46 seconds" exit="success"/><hosts up="1" down="0" total="1"/>
</runstats>
## However, anytime I use the following code to get the NSE script results, the dictionary returned is empty:

nmap_report = NmapParser.parse_fromfile('smb-os-test.xml')
host = nmap_report.get_host_byid('192.168.31.205')
svc = host.get_service(139)
nse_results = svc.scripts_results()
print nse_results
## {}

This is what svc.get_dict() shows me:
{'banner': '',
 'id': 'tcp.139',
 'port': '139',
 'protocol': 'tcp',
 'service': 'netbios-ssn',
 'state': 'open'}

I also tried this for port 445, but get the same results. Am I doing something wrong? Let me know if you need any additional info.

**Comment by brizzbane** [comment]
I've downloaded straight from github as opposed to PIP install, and still have issue of dict showing {} when printing it out.  I print out nmap_report = NmapParser.parse(nmap_proc.stdout), and see values in the XML.

What am I doing wrong :\?
