### ISSUE TITLE
Using OS detection with Nmap 5.61TEST5 causes hang

### ISSUE THREAD

**Issue by wrycu** [savon-noir/python-libnmap#39]
nmap = NmapProcess("some_subnet", options="-O") 
rc = nmap.sudo_run_background()

The above code causes libnmap to freak out and never return from the execution of Nmap (FUTEX_WAIT_PRIVATE, according to a quick strace).  Performing a scan with the same command-line options (shown via nmap.get_command_line) runs fine.

**Comment by savon-noir** [comment]
should be fixed in https://github.com/savon-noir/python-libnmap/commit/5d52591fdd589c8f48ed1e89674fb8f7c1c7d82b
