### ISSUE TITLE
'NmapOSFingerprint' object has no attribute 'osclasses'

### ISSUE THREAD

**Issue by alioth310** [savon-noir/python-libnmap#46]
I got this AttributeError when using `os_class_probabilities()`

    def nmap(target):
        nmap_proc = NmapProcess(targets=target, options="-O")
        nmap_proc.sudo_run()
        
        if nmap_proc.rc == 0:
            nmap_report = nmap_proc.stdout
        else:
            return
        
        try:
            parsed = NmapParser.parse(nmap_report)
        except NmapParserException, e:
            return
        
        for host in parsed.hosts:
            osclass = host.os_class_probabilities()

Then, I got exception:

    AttributeError: 'NmapOSFingerprint' object has no attribute 'osclasses'

I read the code of libnmap/objects/os.py, and found it only has a method called `osclass`, while method `osclasses` does really not exist.  Is it lost?

When I changed `rval = self.os.osclasses` to `rval = self.os.osclass()` (libnmap/objects/host.py), I got another exception:

    File "/path/libnmap/objects/os.py", line 369, in osclass
      for osmatch_entry in self.osmatches():
    TypeError: 'list' object is not callable

Then I found `osmatches` has decorator `@property`. So it may another bug.

===
And a typo of method `osclass` (libnmap/objects/os.py) :
`_ftstr = "type:{0}|vendor:{1}|osfamily{2}".format(`
->
`_ftstr = "type:{0}|vendor:{1}|osfamily:{2}".format(`

**Comment by savon-noir** [comment]
solved in https://github.com/savon-noir/python-libnmap/commit/4b0dd0ace6b1ff1691bfc6e37841e144cb8ba0c3
