### ISSUE TITLE
remove multiprocessing from libnmap/process.py

### ISSUE THREAD

**Issue by pyoner** [savon-noir/python-libnmap#48]
Why are you use multiprocessing for read nmap stdout?

Here I create version without multiprocessing [removed multiprocessing](https://github.com/pyoner/python-libnmap/commit/0e4ed04070b82331f5c3bd7a56374c4820b215d7#diff-f0f58d7278f97a69b7205cc2c2489174)

**Comment by pyoner** [comment]
here final commit https://github.com/pyoner/python-libnmap/commit/9463b2ed9108930d4726b482ae56e05ca3739961

**Comment by MatthewShao** [comment]
Thank a lot for this version of libnmap!
I found that the original one could not work with the celery.It seems that the multiprocessing is the reason, it comes out a error that "daemonic processes are not allowed to have children ".
Luckily, I found this version and try it on my project with celery.After removing the multiprocessing, it works pretty well.

**Comment by savon-noir** [comment]
https://github.com/savon-noir/python-libnmap/commit/5d52591fdd589c8f48ed1e89674fb8f7c1c7d82b
