### ISSUE TITLE
Traceback on windows

### ISSUE THREAD

**Issue by jahrome** [savon-noir/python-libnmap#50]
Hi,

Seems like windows support is broken:

```
...
    from libnmap.process import NmapProcess
  File "C:\Python27\lib\site-packages\libnmap\process.py", line 3, in <module>
    import pwd
ImportError: No module named pwd
```

**Comment by savon-noir** [comment]
hello,

i don't think i really intend to support windows :) I think that the error thrown should be easy to fix since this module is only used for sudo. I'll try to fix it. Then i would be glad to have some feedback from a windows user of the lib

Ronald

**Comment by Kais3r00** [comment]
Hello,

Any news about this pwd problem ?

Thanks

**Comment by savon-noir** [comment]
fixed in commit https://github.com/savon-noir/python-libnmap/commit/f6f1f3c7a64541fa70d3ccfa4a3ae38f486e41e3 proposed by @newlog ... kudos to him!
