### ISSUE TITLE
Question get_dict()

### ISSUE THREAD

**Issue by Starow** [savon-noir/python-libnmap#52]
Hello!
Sorry to bother you with this question, but I wonder: 
Why you didn't return more attributes than just [status, hostnames, address] in the function get_dict() such as the MAC adress etc...
Could be useful to make a diff also on the MAC adress & others fields no?

**Comment by savon-noir** [comment]
Hello,

at the time I created the diff and related logic, mac address wasn't yet parsed. I never added support for additional attributes since implementation of diff. 

Never had the need to add more but im open to any good propositions and pull requests :p

**Comment by Starow** [comment]
Okay :)
Thank you for the fast answer!
I proposed a little pull request where mac adress is added.
Up to you to accept it :)
