### ISSUE TITLE
0.6.3 ?

### ISSUE THREAD

**Issue by balloob** [savon-noir/python-libnmap#61]
There have been some fixes since the last release 0.6.2. Would it be possible to get a new release pushed to PyPi?

**Comment by savon-noir** [comment]
yep. i'll update it asap on pypi

**Comment by savon-noir** [comment]
thanks for your comment. It's pushed on pypi!

pip install --upgrade python-libnmap

**Comment by balloob** [comment]
Awesome, thanks!
