### ISSUE TITLE
NmapProcess.run() deadlock with nmap 6.47

### ISSUE THREAD

**Issue by gcarq** [savon-noir/python-libnmap#63]
Hi  @savon-noir,

it seems there is a deadlock in NmapProcess.run().
This issue occurs with: 
``` /usr/bin/nmap -oX - -vvv --stats-every 1s --top-ports 5 --unprivileged -sT 127.0.0.1 ```

Popen.poll() checks if the process is still existent, but the iteration on the stdout.readline never finishes if there is too much output.

Breaking the iteration if the streamline is empty may fix this issue:
```
        while self.__nmap_proc.poll() is None:
            for streamline in iter(self.__nmap_proc.stdout.readline, ''):
                if not streamline:
                    break
                self.__stdout += str(streamline)
                evnt = self.__process_event(streamline)
                if self.__nmap_event_callback and evnt:
                    self.__nmap_event_callback(self)
```

**Comment by savon-noir** [comment]
strange. need to test this out. a bit overloaded but i'll check asap
thanks for the bug report

**Comment by bbc2** [comment]
It looks like you can trigger the bug with a command as simple as

```python
nm = NmapProcess('scanme.nmap.org', options='-p80')
nm.run()
```

The nmap subprocess runs fine but as soon as it outputs the result, the parent process hangs on the CPU.  I've tried the suggested patch, which avoids this problem, but `nm.stdout` doesn't seem to be correct.  @gcarq Have you checked that?

I've just installed nmap 6.47 and python3 on Debian Jessie and got libnmap 0.6.3 from PyPi.

**Comment by savon-noir** [comment]
hmmm scary :/ ill check this out

**Comment by gparent** [comment]
Any progress on this? I'd like to use this library some day.
