### ISSUE TITLE
NmapParser on XML always returning object as NmapReport instead of NmapHost

### ISSUE THREAD

**Issue by dkade** [savon-noir/python-libnmap#82]
user@work-dev:~/$ cat test.xml | grep -A 3 "\<ports\>" 
\<ports\>\<extraports state="closed" count="997"\>
\<extrareasons reason="conn-refused" count="997"/\>
\</extraports\>
\<port protocol="tcp" portid="53"\>\<state state="open" reason="syn-ack" reason_ttl="0"/\>\<service name="domain" method="probed" conf="10"/\>\<script id="dns-nsid" output="&#xa;  bind.version: 9.9.5-9+deb8u5-Debian"\>\<elem key="bind.version"\>9.9.5-9+deb8u5-Debian\</elem\>

\>\>\> nmap_report = NmapParser.parse_fromfile('test.xml')
\>\>\> type(nmap_report)
<class 'libnmap.objects.report.NmapReport'>
\>\>\>

This should have created an object as NmapHost correct?

Thank you

**Comment by dkade** [comment]
Forget it, just found out how to do it, if you are having this issue you can get NmapHost object from the NmapReport object by calling get_host_byid('ip-address') :
```` python
rep = NmapParser.parse_fromfile('xml/test.xml')
nmap_host = rep.get_host_byid('127.0.0.1')
print (nmap_host.get_open_ports())
````

**Comment by savon-noir** [comment]
yep. sorry, forgot to answer this one. It is designed as is. nmap scan returns a report which contains a list of hosts accessible via either the method you've mentioned or rep.hosts which is a pure python array of NmapHost objects. You could iterate on this and do some checks with the NmapHost API.
