### ISSUE TITLE
process.py returns 'Object has no attribute Format'

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [savon-noir/python-libnmap#97]
Running the process.py from windows cmd. 

Getting an attribute error: 'Object has no attribute Format'

using these:
def __init__(self, targets="google.com",
                 options="-T4 -A -v", event_callback=None, safe_mode=True, fqp=None):

All other things are unchanged. I would like some guidance to where i should edit the process.py file to get the nmap output on my desktop in XML.

**Comment by savon-noir** [comment]
This issue looks like a bad usage of the package. libnmap is a library and should be used, not modified to run nmap scan. please consider looking at available examples directory.

e.g.: examples/proc_nmap_like.py
